let questions = [
    {
        "question": "Von wem stammt der berühmte Satz „Ich denke, also bin ich“?",
        "answer1": "John Fitzgerald Kennedy",
        "answer2": "George Walker Bush",
        "answer3": "René Descartes",
        "answer4": "Julius Caesar",
        "right_answer": 3,
    },
    {
        "question": "Was ist der längste Fluss der Welt?",
        "answer1": "Der Amazonas",
        "answer2": "Der Nil",
        "answer3": "Der Rhein",
        "answer4": "Der Niger",
        "right_answer": 2,
    },
    {
        "question": "In welchem dieser Filme spielt Leonardo DiCaprio NICHT mit?",
        "answer1": "The Wolf of Wallstreet",
        "answer2": "12 Years a Slave",
        "answer3": "Aviator",
        "answer4": "The Revenant",
        "right_answer": 2,
    },
    {
        "question": "Welche Blumenzwiebeln wurden früher als Zahlungsmittel genutzt?",
        "answer1": "Krokusse",
        "answer2": "Lilien",
        "answer3": "Gladiolen",
        "answer4": "Tulpen",
        "right_answer": 4,
    },
    {
        "question": "Was ist ein Falchion?",
        "answer1": "Ein Schwert",
        "answer2": "Ein Tier",
        "answer3": "Ein Gericht",
        "answer4": "Ein Kleidungsstück",
        "right_answer": 1,
    },
    {
        "question": "Aus welchem Land kommt die Band AC/DC?",
        "answer1": "Aus Neuseeland",
        "answer2": "Aus den USA",
        "answer3": "Aus Australien",
        "answer4": "Aus England",
        "right_answer": 3,
    },
    {
        "question": "Mit was beschäftigt sich ein Ornithologe?",
        "answer1": "Vogelarten",
        "answer2": "Insekten",
        "answer3": "Fossilien",
        "answer4": "Korallen",
        "right_answer": 1,
    },
    {
        "question": "Was verbirgt sich hinter einer Konklave.",
        "answer1": "Die Befreiung der Sklaverei in den Südstaaten",
        "answer2": "Eine Papstwahl",
        "answer3": "Ein Musikstück",
        "answer4": "Eine besondere Form der Kunst",
        "right_answer": 2,
    },
    ];